# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'Noeglen' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Noeglen

    # Fluid-slider
    pod 'fluid-slider'
    
    # Firebase
    pod 'Firebase/Analytics'
    pod 'Firebase/Core'
    pod 'Firebase/Firestore'

    # Pods for PodTest
    pod 'Fabric'
    pod 'Crashlytics'



end
